/** ===================================================================
 *  POS Multi-Store — Apps Script backend
 *  Bind this script to the "POS_MultiStore_Database" spreadsheet
 *  (a brand-new sheet, independent from the old POS_Water_Database).
 *
 *  SETUP (one time):
 *  1. Open the spreadsheet -> Extensions > Apps Script.
 *  2. Delete any starter code, paste this whole file in.
 *  3. In the toolbar function dropdown, select "setup" and click Run.
 *     (First run asks for permission - approve it.) This creates all
 *     tabs (Stores, Users, Inventory, Couriers) with headers and seed
 *     data, plus one separate Orders tab PER STORE (e.g. Orders_shop_a,
 *     Orders_shop_b) so each store's orders are kept apart.
 *  4. Deploy > New deployment > type "Web app".
 *     - Execute as: Me
 *     - Who has access: Anyone
 *  5. Copy the Web app URL and paste it into GAS_URL in app.js.
 *
 *  UPDATING AN EXISTING SHEET (features added after your first setup):
 *  Run these once each, from the function dropdown, instead of re-running
 *  `setup` (which only touches brand-new sheets):
 *    - `migrateBundlePricing`  — adds bundle_group/bundle_price to Inventory
 *    - `migrateImageColumns`   — adds logo_url/avatar_url/image_url columns
 *    - `migrateCostPrices`     — adds cost_price to Inventory (courier commission)
 *    - `migrateCommissionPaidColumn` — adds commission_paid to existing Orders_* tabs
*    - `migrateSettingsSheet`   — adds the Settings tab (courier_commission_rate) to an
*                                 existing spreadsheet
*    - `migrateCustomersSheet`  — adds the Customers tab (customer directory)
*    - `migrateCustomerOrderColumns` — adds customer_name/phone/address/note to
*                                 existing Orders_* tabs
 *    - `migrateClientUidColumn` — adds client_uid to existing Orders_* tabs (makes a
 *                                 retry after a dropped connection duplicate-safe)
 *    - `migrateAvatarUrls`     — re-saves old-format avatar photos as data URIs
 *    - `fixUsersSheet`         — repairs the Users sheet if columns ever get
 *                                 out of sync with their headers
 * =================================================================== */

const SS_ID = '1S2AXBIOSbLNGOUU3kD23H6j-ZP0ttsou8kDkSOkuFcA'; // POS_MultiStore_Database

const SHEET_STORES = 'Stores';
const SHEET_USERS = 'Users';
const SHEET_INVENTORY = 'Inventory';
const SHEET_COURIERS = 'Couriers';
const SHEET_SETTINGS = 'Settings'; // key/value config the owner can edit directly in the sheet
const SHEET_CUSTOMERS = 'Customers'; // customer directory - see upsertCustomerIfNeeded_
const ORDERS_PREFIX = 'Orders_'; // each store gets its own tab: Orders_<store_id>
const ORDERS_HEADERS = [
  'order_id', 'timestamp', 'store_id', 'client_id', 'user_name',
  'customer_name', 'customer_phone', 'customer_address', 'customer_note',
  // customer_* columns are a SNAPSHOT of what was known/typed at the moment this
  // order was saved (see upsertCustomerIfNeeded_) - they stay accurate for this
  // delivery even if the customer's address in the Customers sheet changes later.
  'items_json', 'item_summary', 'total', 'courier', 'status',
  'commission_paid', // TRUE once the owner has paid out this order's courier commission
  'client_uid',      // random id generated by the phone per save attempt - lets a
                     // retry after a dropped connection re-use the same row instead
                     // of creating a duplicate order (see submitOrder)
];

// status values written into the Orders_* sheets
const ORDER_STATUS_SAVED = 'บันทึกแล้ว';
const ORDER_STATUS_VOID = 'ยกเลิก';

function getSS_() {
  return SpreadsheetApp.openById(SS_ID);
}

/** ================== ONE-TIME SETUP ================== */
function setup() {
  const ss = getSS_();

  // remove default "Sheet1" once real tabs exist
  const defaultSheet = ss.getSheetByName('Sheet1');

  // logo_url: relative/absolute path to a real logo image (e.g. "images/stores/shop_a.png").
  // Leave blank to keep showing the colored circle + logo_emoji as before.
  const storeRows = [
    ['shop_a', 'ผู้ชายขายน้ำ', '💧', '#8B7FD6', true, ''],
    ['shop_b', 'นาแบะโอนลี่', '🍘', '#8B7FD6', true, ''],
  ];

  ensureSheet_(ss, SHEET_STORES, ['store_id', 'name', 'logo_emoji', 'color', 'active', 'logo_url'], storeRows);

  // avatar_url is filled in automatically when a user uploads a profile photo
  // from the "new user" screen (saved to Google Drive, see doPost/registerUser).
  ensureSheet_(ss, SHEET_USERS, ['client_id', 'name', 'permission', 'created_at', 'last_seen', 'avatar_url'], []);

  // bundle_group / bundle_price: items that share the same bundle_group pool their
  // quantities together — every complete group of 3 (across sizes) is charged at
  // bundle_price, the leftover (0-2 pcs) at the item's own regular price. Leave both
  // blank for items that don't have a bundle promo.
  // image_url: relative/absolute path to a product photo (e.g. "images/products/ammarit600.png").
  // Leave blank to keep showing the plain colored box as before.
  // cost_price: what the shop pays per pack — used only for the courier commission
  // panel (see getCourierEarnings_ / doGet action=getCourierEarnings). Leave blank
  // for items where cost isn't tracked; they're simply skipped in that calculation.
  ensureSheet_(ss, SHEET_INVENTORY, [
    'store_id', 'item_id', 'item_name', 'price', 'sort_order', 'active', 'bundle_group', 'bundle_price', 'image_url', 'cost_price',
  ], [
    ['shop_a', 'a1', 'Ammarit 600ml x3', 110, 1, true, '', '', '', 75],
    ['shop_a', 'a2', 'Ammarit 1500ml x3', 110, 2, true, '', '', '', 75],
    ['shop_a', 'a3', 'Ammarit 600ml', 40, 3, true, 'ammarit_single', 110, '', 25],
    ['shop_a', 'a4', 'Ammarit 1500ml', 40, 4, true, 'ammarit_single', 110, '', 25],
    ['shop_a', 'a5', 'Crystal 600ml', 55, 5, true, '', '', '', 43.0588],
    ['shop_a', 'a6', 'Crystal 1500ml', 55, 6, true, '', '', '', 43.0588],
    ['shop_a', 'a7', 'Singha 600ml', 55, 7, true, '', '', '', ''],
    ['shop_a', 'a8', 'Singha 1500ml', 55, 8, true, '', '', '', ''],
    ['shop_a', 'a9', 'Ammarit 300ml', 40, 9, true, 'ammarit_single', 110, '', 25],
    ['shop_b', 'b1', 'นาแบะเล็ก', 59, 1, true, '', '', '', ''],
    ['shop_b', 'b2', 'นาแบะใหญ่', 79, 2, true, '', '', '', ''],
    ['shop_b', 'b3', 'ข้าว', 10, 3, true, '', '', '', ''],
  ]);

  ensureSheet_(ss, SHEET_COURIERS, ['courier_id', 'name', 'active'], [
    ['c1', 'ไนซ์', true],
    ['c2', 'เอฟ', true],
    ['c3', 'เทพ', true],
  ]);

  // courier_commission_rate: fraction (0-1) of each line's profit margin (sale
  // price minus cost_price) paid out to the courier — see computeCourierEarnings_.
  // Edit the value cell in this sheet any time to change the payout ratio; no
  // code change or redeploy needed. 0.8 was chosen 2026-09 so that a standard
  // Ammarit x3 set (price 100, cost_price 75, margin 25) pays exactly 20.-/round
  // after the price was cut from 110 to 100.
  ensureSheet_(ss, SHEET_SETTINGS, ['setting_key', 'setting_value'], [
    ['courier_commission_rate', 0.8],
  ]);

  // Customer directory used by the "checkout" popup (see doGet action=getCustomers
  // and upsertCustomerIfNeeded_): typing a name/phone that matches a row here
  // auto-fills address/phone/note; typing one that doesn't match offers to add
  // a new row. address/phone/note may be blank for a walk-in customer that was
  // never saved here - only the order's own customer_* snapshot columns get filled then.
  ensureSheet_(ss, SHEET_CUSTOMERS, ['customer_id', 'name', 'phone', 'address', 'note', 'created_at'], []);

  // one Orders tab per store, kept fully separate from each other
  storeRows.forEach(row => {
    const storeId = row[0];
    ensureSheet_(ss, ORDERS_PREFIX + storeId, ORDERS_HEADERS, []);
  });

  // legacy single "Orders" tab from an earlier version of this script -
  // safe to remove only if it's still empty (no real data in it)
  const legacyOrders = ss.getSheetByName('Orders');
  if (legacyOrders && legacyOrders.getLastRow() <= 1) ss.deleteSheet(legacyOrders);

  if (defaultSheet) ss.deleteSheet(defaultSheet);

  SpreadsheetApp.flush();
}

/** Returns (creating if needed) the Orders tab that belongs to a given store_id. */
function getOrdersSheet_(ss, storeId) {
  return ensureSheet_(ss, ORDERS_PREFIX + storeId, ORDERS_HEADERS, []);
}

/** ================== ONE-TIME MIGRATION (only needed if Inventory already
 *  existed before bundle pricing was added) ================== */
function migrateBundlePricing() {
  const ss = getSS_();
  const sh = ss.getSheetByName(SHEET_INVENTORY);
  const values = sh.getDataRange().getValues();
  const headers = values[0];

  let bundleGroupCol = headers.indexOf('bundle_group');
  let bundlePriceCol = headers.indexOf('bundle_price');

  if (bundleGroupCol === -1) {
    sh.getRange(1, headers.length + 1).setValue('bundle_group');
    bundleGroupCol = headers.length;
    headers.push('bundle_group');
  }
  if (bundlePriceCol === -1) {
    sh.getRange(1, headers.length + 1).setValue('bundle_price');
    bundlePriceCol = headers.length;
    headers.push('bundle_price');
  }

  const itemIdCol = headers.indexOf('item_id');
  const ammaritSingles = ['a3', 'a4', 'a9']; // Ammarit 600ml / 1500ml / 300ml (single pieces, 40.- each)

  for (let r = 1; r < values.length; r++) {
    if (ammaritSingles.includes(values[r][itemIdCol])) {
      sh.getRange(r + 1, bundleGroupCol + 1).setValue('ammarit_single');
      sh.getRange(r + 1, bundlePriceCol + 1).setValue(110);
    }
  }

  SpreadsheetApp.flush();
}

/** ================== ONE-TIME MIGRATION (only needed if Stores/Users/Inventory
 *  already existed before the image columns were added) ================== */
function migrateImageColumns() {
  const ss = getSS_();
  addColumnIfMissing_(ss.getSheetByName(SHEET_STORES), 'logo_url');
  addColumnIfMissing_(ss.getSheetByName(SHEET_USERS), 'avatar_url');
  addColumnIfMissing_(ss.getSheetByName(SHEET_INVENTORY), 'image_url');
  SpreadsheetApp.flush();
}

/** ================== ONE-TIME MIGRATION (only needed if Inventory already
 *  existed before cost_price was added) — adds the column if missing and fills
 *  in the known cost for Ammarit/Crystal items (used by the courier commission
 *  panel). Items without a known cost (e.g. Singha) are left blank on purpose
 *  and are simply skipped in the commission calculation. Safe to re-run. */
function migrateCostPrices() {
  const ss = getSS_();
  const sh = ss.getSheetByName(SHEET_INVENTORY);
  addColumnIfMissing_(sh, 'cost_price');

  const headers = sh.getRange(1, 1, 1, sh.getLastColumn()).getValues()[0];
  const itemIdCol = headers.indexOf('item_id') + 1;
  const costCol = headers.indexOf('cost_price') + 1;
  if (itemIdCol === 0 || costCol === 0 || sh.getLastRow() < 2) return;

  const KNOWN_COSTS = {
    a1: 75, a2: 75,       // Ammarit 600ml/1500ml x3 pack (3 x 25)
    a3: 25, a4: 25, a9: 25, // Ammarit 600ml/1500ml/300ml single
    a5: 43.0588, a6: 43.0588, // Crystal 600ml/1500ml
  };

  const itemIds = sh.getRange(2, itemIdCol, sh.getLastRow() - 1, 1).getValues();
  itemIds.forEach((row, i) => {
    const itemId = row[0];
    if (KNOWN_COSTS.hasOwnProperty(itemId)) {
      sh.getRange(i + 2, costCol).setValue(KNOWN_COSTS[itemId]);
    }
  });
  SpreadsheetApp.flush();
}

/** ================== ONE-TIME MIGRATION (only needed if an Orders_<store>
 *  tab already existed before commission_paid was added) — adds the column to
 *  every existing Orders_* tab. New tabs created after this point already get
 *  it automatically via ORDERS_HEADERS. Safe to re-run. */
function migrateCommissionPaidColumn() {
  const ss = getSS_();
  ss.getSheets().forEach(sh => {
    if (sh.getName().indexOf(ORDERS_PREFIX) === 0) {
      addColumnIfMissing_(sh, 'commission_paid');
    }
  });
  SpreadsheetApp.flush();
}

/** ================== ONE-TIME MIGRATION (only needed if the spreadsheet
 *  was created before the Settings tab existed) — adds it with the current
 *  default commission rate, without touching anything else. Safe to re-run:
 *  if the Settings tab (or the courier_commission_rate row) already exists,
 *  this leaves whatever value the owner has since typed in alone. */
function migrateSettingsSheet() {
  const ss = getSS_();
  ensureSheet_(ss, SHEET_SETTINGS, ['setting_key', 'setting_value'], [
    ['courier_commission_rate', 0.8],
  ]);
  SpreadsheetApp.flush();
}

/** ================== ONE-TIME MIGRATION (only needed if the spreadsheet
 *  was created before the Customers tab existed) — adds it, empty. Safe to
 *  re-run: does nothing if the tab is already there. */
function migrateCustomersSheet() {
  const ss = getSS_();
  ensureSheet_(ss, SHEET_CUSTOMERS, ['customer_id', 'name', 'phone', 'address', 'note', 'created_at'], []);
  SpreadsheetApp.flush();
}

/** ================== ONE-TIME MIGRATION (only needed if an Orders_<store>
 *  tab already existed before the customer_* columns were added) — adds the
 *  4 columns to every existing Orders_* tab. New tabs created after this
 *  point already get them automatically via ORDERS_HEADERS. Safe to re-run;
 *  existing order rows simply get blank values in the new columns (there's
 *  no way to know who ordered them retroactively). */
function migrateCustomerOrderColumns() {
  const ss = getSS_();
  ss.getSheets().forEach(sh => {
    if (sh.getName().indexOf(ORDERS_PREFIX) === 0) {
      addColumnIfMissing_(sh, 'customer_name');
      addColumnIfMissing_(sh, 'customer_phone');
      addColumnIfMissing_(sh, 'customer_address');
      addColumnIfMissing_(sh, 'customer_note');
    }
  });
  SpreadsheetApp.flush();
}

/** ================== ONE-TIME MIGRATION — adds the client_uid column to every
 *  existing Orders_* tab (used for duplicate-safe retries). Safe to re-run. */
function migrateClientUidColumn() {
  const ss = getSS_();
  ss.getSheets().forEach(sh => {
    if (sh.getName().indexOf(ORDERS_PREFIX) === 0) {
      addColumnIfMissing_(sh, 'client_uid');
    }
  });
  SpreadsheetApp.flush();
}

function addColumnIfMissing_(sh, headerName) {
  const headers = sh.getRange(1, 1, 1, sh.getLastColumn()).getValues()[0];
  if (headers.indexOf(headerName) === -1) {
    sh.getRange(1, headers.length + 1).setValue(headerName);
  }
}

/** ================== ONE-TIME REPAIR (only needed if the Users sheet's
 *  columns got out of sync — e.g. `addColumnIfMissing_` added a header past a
 *  blank leftover column, so the header text and the actual data ended up in
 *  different columns). Rebuilds the sheet with clean, correctly-matched
 *  columns: client_id, name, permission, created_at, last_seen, avatar_url.
 *  It finds avatar photo data by content (a data: URI or a Drive link) even
 *  if its header text is missing/blank, so no data gets lost. Safe to run
 *  more than once. */
function fixUsersSheet() {
  const ss = getSS_();
  const sh = ss.getSheetByName(SHEET_USERS);
  const values = sh.getDataRange().getValues();
  if (values.length === 0) return;

  const oldHeaders = values[0];
  const col_ = (name) => oldHeaders.indexOf(name);

  let avatarColIdx = col_('avatar_url');
  if (avatarColIdx === -1) {
    // header text is missing/blank somewhere - find the column that actually
    // holds avatar-looking data instead
    outer:
    for (let c = 0; c < oldHeaders.length; c++) {
      for (let r = 1; r < values.length; r++) {
        const v = String(values[r][c] || '');
        if (v.indexOf('data:') === 0 || v.indexOf('drive.google.com') !== -1 || v.indexOf('googleusercontent.com') !== -1) {
          avatarColIdx = c;
          break outer;
        }
      }
    }
  }

  const newHeaders = ['client_id', 'name', 'permission', 'created_at', 'last_seen', 'avatar_url'];
  const idx = {
    client_id: col_('client_id'), name: col_('name'), permission: col_('permission'),
    created_at: col_('created_at'), last_seen: col_('last_seen'),
  };

  const newRows = values.slice(1).map(row => [
    idx.client_id > -1 ? row[idx.client_id] : '',
    idx.name > -1 ? row[idx.name] : '',
    idx.permission > -1 ? row[idx.permission] : '',
    idx.created_at > -1 ? row[idx.created_at] : '',
    idx.last_seen > -1 ? row[idx.last_seen] : '',
    avatarColIdx > -1 ? row[avatarColIdx] : '',
  ]);

  sh.clear();
  sh.getRange(1, 1, 1, newHeaders.length).setValues([newHeaders]);
  if (newRows.length) sh.getRange(2, 1, newRows.length, newHeaders.length).setValues(newRows);
  sh.setFrozenRows(1);
  SpreadsheetApp.flush();
}

function ensureSheet_(ss, name, headers, seedRows) {
  let sh = ss.getSheetByName(name);
  if (!sh) sh = ss.insertSheet(name);
  if (sh.getLastRow() === 0) {
    sh.appendRow(headers);
    sh.setFrozenRows(1);
    if (seedRows.length) sh.getRange(2, 1, seedRows.length, headers.length).setValues(seedRows);
  }
  return sh;
}

/** ================== HELPERS ================== */

/** Reads one numeric value out of the Settings tab (setting_key/setting_value
 *  columns), e.g. getSettingNumber_(ss, 'courier_commission_rate', 0.57).
 *  Falls back to defaultValue if the Settings tab, the row, or a parseable
 *  number isn't there yet (e.g. before migrateSettingsSheet has been run) -
 *  so this is always safe to call even on an older spreadsheet. */
function getSettingNumber_(ss, key, defaultValue) {
  const sh = ss.getSheetByName(SHEET_SETTINGS);
  if (!sh) return defaultValue;
  const rows = sheetToObjects_(sh);
  const row = rows.find(r => String(r.setting_key || '').trim() === key);
  if (!row) return defaultValue;
  const n = Number(row.setting_value);
  return isNaN(n) ? defaultValue : n;
}

function sheetToObjects_(sh) {
  const values = sh.getDataRange().getValues();
  if (values.length < 2) return [];
  const headers = values[0];
  return values.slice(1)
    .filter(row => row.some(c => c !== '' && c !== null))
    .map(row => {
      const obj = {};
      headers.forEach((h, i) => (obj[h] = row[i]));
      return obj;
    });
}

function jsonOut_(obj) {
  return ContentService.createTextOutput(JSON.stringify(obj)).setMimeType(ContentService.MimeType.JSON);
}

// new Date().toISOString() always returns UTC time (the trailing "Z"), which
// is 7 hours behind Thailand — that's why timestamps in the sheet looked
// "wrong". This formats using the Asia/Bangkok timezone instead so what's
// written matches the real local time.
function nowIso_() {
  return Utilities.formatDate(new Date(), 'Asia/Bangkok', 'yyyy-MM-dd HH:mm:ss');
}

// Sheets can hand back a checkbox column as a real boolean or, if someone typed
// it in by hand, as the text "TRUE" - treat either as true.
function isTrue_(v) {
  return v === true || String(v).trim().toUpperCase() === 'TRUE';
}

/** ================== AVATAR STORAGE ==================
 *  Three different Google Drive hotlink formats were all tried and all turned
 *  out unreliable when embedded as an <img> from an outside website (and
 *  returning a raw Blob from doGet isn't supported by Apps Script Web Apps —
 *  it errors with "script completed but the return value isn't a supported
 *  result type"). The reliable fix: skip external hosting entirely and store
 *  the photo as a data: URI directly in the Users sheet. The browser renders
 *  a data: URI instantly with zero extra network requests, so there's nothing
 *  that can fail to load. The photo is already resized/compressed client-side
 *  (app.js) before it gets here, so the resulting string comfortably fits in
 *  a single Sheets cell (well under the ~50,000 character cell limit). */
function buildAvatarDataUri_(base64Data, mimeType) {
  return 'data:' + (mimeType || 'image/jpeg') + ';base64,' + base64Data;
}

/** ================== ONE-TIME MIGRATION (only needed if avatars were saved
 *  using an older Drive-hotlink URL format from an earlier version of this
 *  script — re-downloads the photo from Drive and re-saves it as a data: URI
 *  in the sheet, so nobody has to re-upload their photo). */
function migrateAvatarUrls() {
  const ss = getSS_();
  const sh = ss.getSheetByName(SHEET_USERS);
  const values = sh.getDataRange().getValues();
  const headers = values[0];
  const avatarCol = headers.indexOf('avatar_url');
  if (avatarCol === -1) return;

  for (let r = 1; r < values.length; r++) {
    const url = String(values[r][avatarCol] || '');
    if (url.startsWith('data:')) continue; // already migrated

    const match = url.match(/thumbnail\?id=([^&]+)/)
      || url.match(/googleusercontent\.com\/d\/([^/?&]+)/)
      || url.match(/[?&]id=([^&]+)/);
    if (!match) continue;

    try {
      const blob = DriveApp.getFileById(match[1]).getBlob();
      const dataUri = buildAvatarDataUri_(Utilities.base64Encode(blob.getBytes()), blob.getContentType());
      sh.getRange(r + 1, avatarCol + 1).setValue(dataUri);
    } catch (err) {
      // file may no longer exist / not accessible - leave the cell as-is
    }
  }
  SpreadsheetApp.flush();
}

/** ================== BUNDLE PRICING ==================
 *  Items that share the same bundle_group (e.g. Ammarit 600ml / 1500ml / 300ml,
 *  all sold single at 40.-) pool their quantities together: every complete group
 *  of 3 pieces (any mix of sizes) is charged bundle_price (110.-), the remaining
 *  0-2 pieces are charged at each item's own regular price. */
function calcBundleTotal_(qty, singlePrice, bundlePrice) {
  if (!bundlePrice) return qty * singlePrice;
  const bundles = Math.floor(qty / 3);
  const rem = qty % 3;
  return bundles * bundlePrice + rem * singlePrice;
}

/** Computes a line_total for every item in the order, pooling qty across items
 *  that share the same bundle_group before applying bundle pricing, then splits
 *  the group's total back across each item's line proportionally (remainder on
 *  the last line so the lines always sum exactly to the group/order total).
 *  invById: { item_id: { bundle_group, bundle_price, ... } } from the Inventory sheet. */
function calcLineTotals_(items, invById) {
  const groups = {}; // key -> { qty, indices, singlePrice, bundlePrice }

  items.forEach((it, idx) => {
    const inv = invById[String(it.item_id)] || {};
    const singlePrice = Number(it.price || 0);
    const bundleGroup = inv.bundle_group ? String(inv.bundle_group) : '';
    const bundlePrice = bundleGroup ? Number(inv.bundle_price || 0) : 0;
    const key = bundleGroup || ('__single__' + it.item_id);

    if (!groups[key]) groups[key] = { qty: 0, indices: [], singlePrice, bundlePrice };
    groups[key].qty += Number(it.qty || 0);
    groups[key].indices.push(idx);
  });

  const lineTotals = new Array(items.length).fill(0);

  Object.keys(groups).forEach(key => {
    const g = groups[key];
    const groupTotal = calcBundleTotal_(g.qty, g.singlePrice, g.bundlePrice);
    let allocated = 0;
    g.indices.forEach((idx, i) => {
      const qty = Number(items[idx].qty || 0);
      let lt;
      if (i === g.indices.length - 1) {
        lt = Number((groupTotal - allocated).toFixed(2)); // remainder absorbs rounding drift
      } else {
        lt = Number(((groupTotal * qty) / g.qty).toFixed(2));
        allocated += lt;
      }
      lineTotals[idx] = lt;
    });
  });

  return lineTotals;
}

/** ================== COURIER COMMISSION (shop_a only) ==================
 *  The courier gets a configurable % of the profit margin (sale price minus
 *  cost_price) on every line item they delivered, summed across all orders in
 *  Orders_shop_a and grouped by courier name. Uses each order's already-saved
 *  line_total (which already reflects Ammarit bundle pricing), so this always
 *  matches what was actually charged — never recalculated from scratch.
 *  Items with no cost_price set in Inventory (e.g. Singha) are skipped, not
 *  treated as zero-cost, so they don't inflate the commission.
 *
 *  The rate itself is read from the Settings tab (courier_commission_rate row)
 *  every time this runs, so the owner can change it straight in Google Sheets
 *  without touching code or redeploying — see getSettingNumber_. If that tab
 *  or row is missing (older spreadsheet), DEFAULT_COURIER_COMMISSION_RATE is
 *  used instead.
 *
 *  Orders already marked commission_paid=TRUE are excluded, so this always
 *  shows the amount still OWED since the last payout — see resetCourierEarnings
 *  (doPost) for how the owner marks a courier as "paid" once they've paid them
 *  in person. Nothing is ever deleted, so full order history stays intact. */
const DEFAULT_COURIER_COMMISSION_RATE = 0.8; // used only if the Settings tab isn't there yet

function computeCourierEarnings_(ss) {
  const ordersSh = ss.getSheetByName(ORDERS_PREFIX + 'shop_a');
  if (!ordersSh) return [];

  const commissionRate = getSettingNumber_(ss, 'courier_commission_rate', DEFAULT_COURIER_COMMISSION_RATE);

  const costById = {};
  sheetToObjects_(ss.getSheetByName(SHEET_INVENTORY)).forEach(r => {
    if (r.cost_price !== '' && r.cost_price !== null && r.cost_price !== undefined) {
      costById[String(r.item_id)] = Number(r.cost_price);
    }
  });

  const totals = {}; // courier name -> total unpaid commission (baht)

  sheetToObjects_(ordersSh).forEach(order => {
    if (isTrue_(order.commission_paid)) return; // already paid out - excluded from the running total
    if (String(order.status || '').trim() === ORDER_STATUS_VOID) return; // cancelled order - no commission
    const courier = String(order.courier || '').trim();
    if (!courier) return;

    let items;
    try {
      items = JSON.parse(order.items_json || '[]');
    } catch (err) {
      return; // malformed row - skip rather than fail the whole report
    }

    let orderCommission = 0;
    items.forEach(it => {
      const cost = costById[String(it.item_id)];
      if (cost === undefined) return; // unknown cost - skip this line entirely
      const qty = Number(it.qty || 0);
      const lineTotal = it.line_total !== undefined ? Number(it.line_total) : Number(it.price || 0) * qty;
      const margin = lineTotal - cost * qty;
      orderCommission += margin * commissionRate;
    });

    totals[courier] = (totals[courier] || 0) + orderCommission;
  });

  return Object.keys(totals)
    .map(name => ({ courier: name, total: Number(totals[name].toFixed(2)) }))
    .sort((a, b) => b.total - a.total);
}

/** ================== CUSTOMERS ==================
 *  Backs the customer name/phone search box in the checkout popup (see
 *  doGet action=getCustomers, app.js ensureCustomersLoaded/renderCustomerSuggestions).
 *  Typing a name or phone that matches an existing row lets the app auto-fill
 *  address/phone/note; typing one that doesn't match offers "+ เพิ่มลูกค้าใหม่".
 *  Kept as its own tab (not mixed into Orders) so one customer's info is
 *  edited/looked-up in one place regardless of how many times they've ordered. */

/** Decides what customer_* values to snapshot into an order row, and - only
 *  when the frontend explicitly asked to (body.save_customer === true AND no
 *  existing customer_id was matched) - appends a brand-new row to the
 *  Customers sheet so the same person auto-fills next time. Returns the 4
 *  snapshot fields to write into the order (never throws; a missing/blank
 *  name just means a walk-in customer with no saved profile). */
function upsertCustomerIfNeeded_(ss, body) {
  const name = String(body.customer_name || '').trim();
  const phone = String(body.customer_phone || '').trim();
  const address = String(body.customer_address || '').trim();
  const note = String(body.customer_note || '').trim();

  if (body.customer_id) {
    // an existing customer was picked from the suggestions list - just use
    // what the app sent (already came from the Customers sheet), don't touch
    // the Customers sheet itself here (editing a saved profile is a separate
    // concern, not part of placing an order).
    return { customer_name: name, customer_phone: phone, customer_address: address, customer_note: note };
  }

  if (name && body.save_customer === true) {
    const sh = ss.getSheetByName(SHEET_CUSTOMERS);
    if (sh) {
      const customerId = 'CUS-' + new Date().getTime();
      sh.appendRow(buildOrderRow_(sh, {
        customer_id: customerId,
        name: name,
        phone: phone,
        address: address,
        note: note,
        created_at: nowIso_(),
      }));
    }
  }

  // walk-in / not saved to the directory - the order still keeps whatever was typed
  return { customer_name: name, customer_phone: phone, customer_address: address, customer_note: note };
}

/** ================== ORDER HISTORY ==================
 *  Reads back the most recent orders of one store so the app can show a
 *  "ประวัติออเดอร์" screen — that way nobody has to open Google Sheets just to
 *  check whether a save actually went through. Read-only: nothing is changed
 *  here. Newest first, capped at `limit` rows so the response stays small
 *  even after thousands of orders. */
function getOrders_(ss, storeId, limit) {
  const sh = ss.getSheetByName(ORDERS_PREFIX + storeId);
  if (!sh) return [];

  const rows = sheetToObjects_(sh);
  const max = Math.max(1, Math.min(Number(limit) || 50, 200));
  const slice = rows.slice(Math.max(0, rows.length - max)); // last N rows in the sheet
  const out = [];

  for (let i = slice.length - 1; i >= 0; i--) { // reverse -> newest first
    const r = slice[i];
    let items = [];
    try {
      items = JSON.parse(r.items_json || '[]');
    } catch (err) {
      items = []; // malformed row - still show the order, just without its detail lines
    }
    out.push({
      order_id: r.order_id,
      timestamp: formatTimestamp_(r.timestamp),
      client_id: r.client_id,
      user_name: r.user_name,
      customer_name: r.customer_name || '',
      customer_phone: r.customer_phone || '',
      customer_address: r.customer_address || '',
      customer_note: r.customer_note || '',
      item_summary: r.item_summary,
      total: Number(r.total || 0),
      courier: r.courier,
      status: String(r.status || ''),
      items: items,
    });
  }
  return out;
}

/** Timestamps are written as plain "yyyy-MM-dd HH:mm:ss" text, but if someone
 *  retypes a cell in Sheets it can come back as a real Date — normalise both
 *  to the same string so the app never has to guess. */
function formatTimestamp_(v) {
  if (v instanceof Date) return Utilities.formatDate(v, 'Asia/Bangkok', 'yyyy-MM-dd HH:mm:ss');
  return String(v || '');
}

/** Builds an Orders row from an object, matching values to columns BY HEADER
 *  NAME — so adding/reordering columns in the sheet can never shift data into
 *  the wrong column. */
function buildOrderRow_(sh, values) {
  const headers = sh.getRange(1, 1, 1, sh.getLastColumn()).getValues()[0];
  return headers.map(h => (values.hasOwnProperty(h) ? values[h] : ''));
}

/** Looks for an already-saved order with this client_uid (only scans the tail
 *  of the sheet — a retry always follows within seconds of the original). */
function findOrderByClientUid_(sh, clientUid) {
  const lastRow = sh.getLastRow();
  if (lastRow < 2) return null;
  const headers = sh.getRange(1, 1, 1, sh.getLastColumn()).getValues()[0];
  const uidCol = headers.indexOf('client_uid');
  const idCol = headers.indexOf('order_id');
  const totalCol = headers.indexOf('total');
  if (uidCol === -1) return null;

  const scan = Math.min(50, lastRow - 1);
  const startRow = lastRow - scan + 1;
  const data = sh.getRange(startRow, 1, scan, headers.length).getValues();
  for (let i = data.length - 1; i >= 0; i--) {
    if (String(data[i][uidCol]) && String(data[i][uidCol]) === String(clientUid)) {
      return { order_id: data[i][idCol], total: Number(data[i][totalCol] || 0) };
    }
  }
  return null;
}

/** ================== GET (read-only queries) ================== */
function doGet(e) {
  const action = e.parameter.action;
  const ss = getSS_();

  try {
    if (action === 'getStores') {
      const stores = sheetToObjects_(ss.getSheetByName(SHEET_STORES)).filter(s => s.active);
      return jsonOut_({ ok: true, stores });
    }

    if (action === 'getInventory') {
      const storeId = e.parameter.store_id;
      const items = sheetToObjects_(ss.getSheetByName(SHEET_INVENTORY))
        .filter(i => i.active && (!storeId || i.store_id === storeId))
        .sort((a, b) => a.sort_order - b.sort_order);
      return jsonOut_({ ok: true, items });
    }

    if (action === 'getCouriers') {
      const couriers = sheetToObjects_(ss.getSheetByName(SHEET_COURIERS)).filter(c => c.active);
      return jsonOut_({ ok: true, couriers });
    }

    if (action === 'getUser') {
      const clientId = e.parameter.client_id;
      const users = sheetToObjects_(ss.getSheetByName(SHEET_USERS));
      const user = users.find(u => u.client_id === clientId);
      return jsonOut_({ ok: true, user: user || null });
    }

    if (action === 'getCourierEarnings') {
      return jsonOut_({ ok: true, earnings: computeCourierEarnings_(ss) });
    }

    if (action === 'getCustomers') {
      const customers = sheetToObjects_(ss.getSheetByName(SHEET_CUSTOMERS));
      return jsonOut_({ ok: true, customers });
    }

    if (action === 'getOrders') {
      const storeId = e.parameter.store_id;
      if (!storeId) return jsonOut_({ ok: false, error: 'missing store_id' });
      return jsonOut_({ ok: true, orders: getOrders_(ss, storeId, e.parameter.limit) });
    }

    return jsonOut_({ ok: false, error: 'unknown action' });
  } catch (err) {
    return jsonOut_({ ok: false, error: String(err) });
  }
}

/** ================== POST (mutations) ================== */
function doPost(e) {
  try {
    const body = JSON.parse(e.postData.contents || '{}');
    const action = body.action;
    const ss = getSS_();

    if (action === 'registerUser') {
      const sh = ss.getSheetByName(SHEET_USERS);
      const headers = sh.getRange(1, 1, 1, sh.getLastColumn()).getValues()[0];
      const users = sheetToObjects_(sh);
      let user = users.find(u => u.client_id === body.client_id);

      let avatarUrl = user ? user.avatar_url : '';
      if (body.avatar_base64) {
        avatarUrl = buildAvatarDataUri_(body.avatar_base64, body.avatar_mime);
      }

      if (!user) {
        // build the row by header name (not by hardcoded position), so this
        // still works correctly no matter what order the columns are in
        const row = headers.map(h => {
          if (h === 'client_id') return body.client_id;
          if (h === 'name') return body.name || 'ผู้ใช้งาน';
          if (h === 'permission') return body.permission || 'Staff';
          if (h === 'created_at' || h === 'last_seen') return nowIso_();
          if (h === 'avatar_url') return avatarUrl || '';
          return '';
        });
        sh.appendRow(row);
        user = {
          client_id: body.client_id,
          name: body.name || 'ผู้ใช้งาน',
          permission: body.permission || 'Staff',
          avatar_url: avatarUrl || '',
        };
      } else {
        const rowIdx = users.findIndex(u => u.client_id === body.client_id) + 2;
        const lastSeenCol = headers.indexOf('last_seen') + 1;
        if (lastSeenCol > 0) sh.getRange(rowIdx, lastSeenCol).setValue(nowIso_());
        if (body.avatar_base64) {
          const avatarCol = headers.indexOf('avatar_url') + 1;
          if (avatarCol > 0) {
            sh.getRange(rowIdx, avatarCol).setValue(avatarUrl);
            user.avatar_url = avatarUrl;
          }
        }
      }
      return jsonOut_({ ok: true, user });
    }

    if (action === 'resetCourierEarnings') {
      // marks every currently-unpaid shop_a order for this courier as
      // commission_paid=TRUE - use this once you've actually paid them out in
      // person. Nothing is deleted; the order rows (and their real revenue
      // total) stay in Orders_shop_a forever for your records. The running
      // "รายได้คนส่ง" total simply drops back to 0 for that courier and starts
      // accumulating again from their next delivery.
      const ordersSh = ss.getSheetByName(ORDERS_PREFIX + 'shop_a');
      if (!ordersSh) return jsonOut_({ ok: false, error: 'ยังไม่มีออเดอร์ของร้านนี้' });

      const headers = ordersSh.getRange(1, 1, 1, ordersSh.getLastColumn()).getValues()[0];
      const courierCol = headers.indexOf('courier');
      const paidCol = headers.indexOf('commission_paid');
      if (courierCol === -1 || paidCol === -1) {
        return jsonOut_({ ok: false, error: 'ไม่พบคอลัมน์ commission_paid - รันฟังก์ชัน migrateCommissionPaidColumn ใน Apps Script ก่อน' });
      }

      const lastRow = ordersSh.getLastRow();
      if (lastRow >= 2) {
        const data = ordersSh.getRange(2, 1, lastRow - 1, headers.length).getValues();
        data.forEach((row, i) => {
          const rowCourier = String(row[courierCol] || '').trim();
          if (rowCourier === String(body.courier || '').trim() && !isTrue_(row[paidCol])) {
            ordersSh.getRange(i + 2, paidCol + 1).setValue(true);
          }
        });
      }
      return jsonOut_({ ok: true });
    }

    if (action === 'voidOrder') {
      // Cancels a mistyped order WITHOUT deleting the row: status becomes
      // "ยกเลิก" and commission_paid is set so the courier commission panel
      // ignores it. Full history stays in the sheet for the record.
      const sh = ss.getSheetByName(ORDERS_PREFIX + body.store_id);
      if (!sh) return jsonOut_({ ok: false, error: 'ไม่พบชีตออเดอร์ของร้านนี้' });

      const headers = sh.getRange(1, 1, 1, sh.getLastColumn()).getValues()[0];
      const idCol = headers.indexOf('order_id');
      const statusCol = headers.indexOf('status');
      if (idCol === -1 || statusCol === -1) return jsonOut_({ ok: false, error: 'โครงสร้างชีตไม่ถูกต้อง' });

      const lastRow = sh.getLastRow();
      if (lastRow < 2) return jsonOut_({ ok: false, error: 'ไม่พบออเดอร์นี้' });

      const data = sh.getRange(2, 1, lastRow - 1, headers.length).getValues();
      for (let i = 0; i < data.length; i++) {
        if (String(data[i][idCol]) === String(body.order_id)) {
          sh.getRange(i + 2, statusCol + 1).setValue(ORDER_STATUS_VOID);
          const paidCol = headers.indexOf('commission_paid');
          if (paidCol > -1) sh.getRange(i + 2, paidCol + 1).setValue(true);
          return jsonOut_({ ok: true });
        }
      }
      return jsonOut_({ ok: false, error: 'ไม่พบออเดอร์นี้' });
    }

    if (action === 'submitOrder') {
      const sh = getOrdersSheet_(ss, body.store_id); // each store writes to its own Orders_<store_id> tab

      // Duplicate guard: the phone sends a client_uid per save attempt. If the
      // connection dropped after the row was written, the retry carries the same
      // uid — we find that row and just report success again instead of saving
      // the same order twice.
      if (body.client_uid) {
        const existing = findOrderByClientUid_(sh, body.client_uid);
        if (existing) return jsonOut_({ ok: true, order_id: existing.order_id, total: existing.total, duplicate: true });
      }

      const orderId = 'ORD-' + new Date().getTime();
      const items = body.items || []; // [{item_id, item_name, qty, price}]

      // total is always recomputed server-side from the Inventory sheet's bundle
      // rules — never trusts the client's total, so pricing stays correct even if
      // the frontend is out of date.
      const invRows = sheetToObjects_(ss.getSheetByName(SHEET_INVENTORY));
      const invById = {};
      invRows.forEach(r => (invById[String(r.item_id)] = r));

      const lineTotals = calcLineTotals_(items, invById);
      const total = lineTotals.reduce((s, v) => s + v, 0);
      const summary = items.map((it, i) => `${it.item_name} x${it.qty} (${lineTotals[i]}.-)`).join(', ');
      const itemsWithTotals = items.map((it, i) => Object.assign({}, it, { line_total: lineTotals[i] }));

      const customerFields = upsertCustomerIfNeeded_(ss, body);

      const timestamp = nowIso_();
      sh.appendRow(buildOrderRow_(sh, Object.assign({
        order_id: orderId,
        timestamp: timestamp,
        store_id: body.store_id,
        client_id: body.client_id,
        user_name: body.user_name || '',
        items_json: JSON.stringify(itemsWithTotals),
        item_summary: summary,
        total: total,
        courier: body.courier || '',
        status: ORDER_STATUS_SAVED,
        commission_paid: '',
        client_uid: body.client_uid || '',
      }, customerFields)));

      return jsonOut_({ ok: true, order_id: orderId, total, timestamp, summary, customer_name: customerFields.customer_name });
    }

    return jsonOut_({ ok: false, error: 'unknown action' });
  } catch (err) {
    return jsonOut_({ ok: false, error: String(err) });
  }
}
